# Generated by Django 3.2.8 on 2021-11-15 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('duration', models.DurationField()),
                ('release_date', models.DateField()),
                ('director', models.CharField(max_length=60)),
                ('main_photo', models.ImageField(upload_to='photos')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(max_length=1)),
                ('description', models.TextField(max_length=500)),
                ('review_date', models.DateField()),
                ('movie_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crudmovies.movie')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crudmovies.user')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_reviews',
            field=models.ManyToManyField(through='crudmovies.Review', to='crudmovies.User'),
        ),
    ]
