# Generated by Django 3.2.8 on 2021-12-10 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('imdbID', models.CharField(max_length=10)),
                ('runtime', models.CharField(max_length=10)),
                ('release_year', models.IntegerField()),
                ('description', models.TextField(max_length=300)),
                ('main_photo', models.URLField()),
                ('imdb_rating', models.FloatField()),
            ],
            options={
                'db_table': 'movie',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'person',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.IntegerField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('description', models.TextField(max_length=500)),
                ('review_date', models.DateField()),
                ('movie', models.ForeignKey(db_column='movie_id', on_delete=django.db.models.deletion.CASCADE, to='crudmovies.movie')),
                ('person', models.ForeignKey(db_column='person_id', on_delete=django.db.models.deletion.CASCADE, to='crudmovies.person')),
            ],
            options={
                'db_table': 'review',
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_reviews',
            field=models.ManyToManyField(through='crudmovies.Review', to='crudmovies.Person'),
        ),
    ]
