# Generated by Django 3.2.8 on 2021-12-10 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudmovies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='imdbID',
            new_name='imdbid',
        ),
    ]
