# Generated by Django 3.2.8 on 2021-11-23 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudmovies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='movie_id',
            new_name='movie',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='user_id',
            new_name='user',
        ),
    ]
